# Generated by Django 4.0.5 on 2022-08-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id_header', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('navbar1', models.CharField(max_length=100)),
                ('navbar2', models.CharField(max_length=100)),
                ('navbar3', models.CharField(max_length=100)),
                ('navbar4', models.CharField(max_length=100)),
                ('navbar5', models.CharField(max_length=100)),
                ('navbar6', models.CharField(max_length=100)),
                ('dropdown1', models.CharField(max_length=100)),
                ('dropdown2', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visimisi',
            fields=[
                ('id_visimisi', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('visimisi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('id_tentangkami', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('desc', models.TextField()),
                ('nama_pengasuh', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tentang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id_prestasi', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/images/prestasi/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prestasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id_daftar', models.AutoField(primary_key=True, serialize=False)),
                ('link_daftar', models.CharField(max_length=100)),
                ('brosur', models.FileField(blank=True, null=True, upload_to='media/images/daftar/')),
                ('email', models.CharField(max_length=100)),
                ('telpon', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daftar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id_home', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('h1', models.CharField(max_length=100)),
                ('nama_pondok', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('telpon', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id_galeri', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/images/galeri/')),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='galeri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ekstrakulikuler',
            fields=[
                ('id_ekstra', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ekstra', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eksa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id_berita', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penulis', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/images/berita/')),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='berita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
