# Generated by Django 4.0.5 on 2022-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='judul',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='berita',
            name='penerbit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
