# Generated by Django 4.0.5 on 2022-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_berita_judul_berita_penerbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='isi',
            field=models.TextField(default=''),
        ),
    ]
