# Generated by Django 4.0.5 on 2022-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_berita_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstrakulikuler',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
