# Generated by Django 4.0.5 on 2022-08-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ekstrakulikuler_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ekstrakulikuler',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='galeri',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.RemoveField(
            model_name='home',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tentangkami',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='visimisi',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Berita',
        ),
        migrations.DeleteModel(
            name='Ekstrakulikuler',
        ),
        migrations.DeleteModel(
            name='Galeri',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Pendaftaran',
        ),
        migrations.DeleteModel(
            name='Prestasi',
        ),
        migrations.DeleteModel(
            name='TentangKami',
        ),
        migrations.DeleteModel(
            name='Visimisi',
        ),
    ]
