# Generated by Django 4.0.5 on 2022-07-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0004_alter_categorybrg_id_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('no_faktur', models.CharField(max_length=200)),
                ('kd_barang', models.CharField(max_length=15)),
                ('jumlah_uang', models.FloatField()),
                ('total_belanja', models.FloatField()),
                ('uang_kembali', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPembelian',
            fields=[
                ('no_faktur', models.CharField(auto_created=True, max_length=200, unique=True)),
                ('Tipetransaksi', models.CharField(choices=[('Jual', 'Jual'), ('Beli', 'Beli')], max_length=4)),
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('jumlah_uang', models.FloatField()),
                ('total_belanja', models.FloatField()),
                ('uang_kembali', models.FloatField()),
                ('tgl', models.DateField(default='17-07-2022')),
                ('code_brg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barang.tblbarang')),
            ],
        ),
    ]
