# Generated by Django 4.0.5 on 2022-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipembelian',
            name='tgl',
            field=models.DateField(default='25-07-2022'),
        ),
    ]
