# Generated by Django 4.0.5 on 2022-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadskripsi',
            name='abstrak',
            field=models.TextField(),
        ),
    ]
