# Generated by Django 4.0.5 on 2022-09-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultavatar.png', null=True, upload_to='profile'),
        ),
    ]
