# Generated by Django 4.0.5 on 2022-10-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_remove_upload_jenis_laporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
        migrations.RemoveField(
            model_name='uploadskripsi',
            name='category',
        ),
    ]
