# Generated by Django 4.0.5 on 2022-08-27 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0002_alter_uploadskripsi_abstrak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karyatulis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites', to='admin1.upload')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('skripsi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites2', to='admin1.uploadskripsi')),
            ],
        ),
    ]
