# Generated by Django 4.0.5 on 2022-10-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_remove_upload_category_remove_uploadskripsi_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='uploadskripsi',
            name='status',
        ),
    ]
