# Generated by Django 4.0.5 on 2022-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_profile_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadskripsi',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
