# Generated by Django 4.0.5 on 2022-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_uploadskripsi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
