# Generated by Django 4.0.5 on 2022-08-27 09:50

import admin1.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0004_upload_favourite_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='bab1',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='bab2',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='bab3',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='bab4',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='bab5',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='cover',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='daftarisi',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='dapus',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='upload',
            name='lampiran',
            field=models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UploadSkripsi',
        ),
    ]
