# Generated by Django 4.0.5 on 2022-10-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_upload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forget_password_token',
        ),
    ]
