# Generated by Django 4.0.5 on 2022-08-27 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0006_remove_upload_bab1_remove_upload_bab2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadskripsi',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav2', to=settings.AUTH_USER_MODEL),
        ),
    ]
