# Generated by Django 4.0.5 on 2022-08-27 18:28

import admin1.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0007_uploadskripsi_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi', models.CharField(choices=[('Informatika', 'Informatika'), ('Teknik Komputer', 'Teknik Komputer'), ('Teknik Elektro', 'Teknik Elektro')], max_length=50)),
                ('judul_laporan', models.CharField(max_length=100)),
                ('tahun_penyelesaian', models.IntegerField()),
                ('abstrak', models.TextField()),
                ('nama_penulis', models.CharField(max_length=50)),
                ('nim_siswa', models.IntegerField()),
                ('lampiran', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('cover', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('daftarisi', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('bab1', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('bab2', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('bab3', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('bab4', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('bab5', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('dapus', models.FileField(blank=True, default='', upload_to='skripsi/', validators=[admin1.validator.validate_file_extension])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('slug', models.SlugField(max_length=120)),
                ('favourite', models.ManyToManyField(blank=True, related_name='fav3', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes3', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skripsi2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
