# Generated by Django 4.0.5 on 2022-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_contoh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contoh',
            name='bab1',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='bab2',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='bab3',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='bab4',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='bab5',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='daftarisi',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='dapus',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='lampiran',
        ),
        migrations.AlterField(
            model_name='contoh',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
