# Generated by Django 4.0.5 on 2022-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_remove_contoh_bab1_remove_contoh_bab2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contoh',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='contoh',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='uploadskripsi',
            name='favourite',
        ),
        migrations.AddField(
            model_name='upload',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadskripsi',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
