# Generated by Django 4.0.5 on 2022-09-04 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0010_remove_contoh_favourite_remove_contoh_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='uploadskripsi',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='contoh',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contoh',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contoh',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='upload',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadskripsi',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav2', to=settings.AUTH_USER_MODEL),
        ),
    ]
