# Generated by Django 4.0.5 on 2022-09-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_remove_upload_is_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favkartul', to='admin1.upload')),
                ('skripsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favskripsi', to='admin1.uploadskripsi')),
            ],
        ),
        migrations.DeleteModel(
            name='Contoh',
        ),
    ]
