# Generated by Django 4.0.5 on 2022-09-04 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0012_bookmark_delete_contoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav4', to=settings.AUTH_USER_MODEL),
        ),
    ]
